### ISSUE TITLE
uninitialized constant MiOS::Interface::Forwardable

### ISSUE THREAD

**Issue by zxjinn** [kreynolds/ruby-mios#10]
Trying to set this up using the instructions in the readme. Here is my setup (using RVM).
Gemfile:
```
source 'https://rubygems.org'
gem 'mios'
```
mios.rb:
```ruby
require 'mios'
mios = MiOS::Interface.new('http://10.10.10.7:3480')
```
Output (after a bundle, of course):
```
$ ruby --version
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux]
$ ruby mios.rb 
/usr/local/rvm/gems/ruby-2.1.1@mios_temporary/gems/mios-0.3.1/lib/mios/interface.rb:4:in `<class:Interface>': uninitialized constant MiOS::Interface::Forwardable (NameError)
	from /usr/local/rvm/gems/ruby-2.1.1@mios_temporary/gems/mios-0.3.1/lib/mios/interface.rb:3:in `<module:MiOS>'
	from /usr/local/rvm/gems/ruby-2.1.1@mios_temporary/gems/mios-0.3.1/lib/mios/interface.rb:1:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rvm/gems/ruby-2.1.1@mios_temporary/gems/mios-0.3.1/lib/mios.rb:4:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from mios.rb:1:in `<main>'
```

I am not sure what's wrong here? I looked through the source and I don't see any references to `Forwardable` except that one line, but I also don't know what `extend` means. So, to test, I cloned this repo, commented out that line, build a new gem and installed that after bumping the version number. Of course, that didn't work :frowning:.

I had this working just fine (somehow?) back in February on ruby-1.9.3-p545 and it has been running just fine since then. However I did a bundle update today, and got two new gems, 0.3.1 of this gem, and 2.6.0.1 of httpclient. I tried rolling back httpclient to what it was before (2.5.3.3) and rolling back ruby from 2.1.1 to 1.9.3 and still no dice.

I'm out of ideas. Any help would be appreciated.

**Comment by zxjinn** [comment]
Left this out, I was running 0.3.0 of this gem before the bundle update.

**Comment by zxjinn** [comment]
I converted my app to use [Traveling Ruby](https://github.com/phusion/traveling-ruby) instead of RVM and things are working there. Not sure exactly what happened..

**Comment by kreynolds** [comment]
Ah, I was going to say that forwardable is a standard library in ruby, it should be there, though perhaps it needs an explicit require in your environment. I was going to ask you to try including that in mios.rb to see if it helped, but it sounds like you've already moved on. Glad you got it working!

**Comment by zxjinn** [comment]
After running into this problem again you were correct: for some reason I have to require `forwardable` first, then `mios` in my environment. Running Ruby 2.1.1 via RVM and this mios gem version 0.3.1. Not looking for an answer as to why it's happening, just posting this here so others can find it.

```ruby
require 'forwardable'
require 'mios'
...
```
