### ISSUE TITLE
Setting the level of a dimmer

### ISSUE THREAD

**Issue by brock** [kreynolds/ruby-mios#11]
Hey @kreynolds

I started trying to implement a dimmer control tonight and found that I can't seem to figure out how to execute the ruby code. I tried this, where `dimmer` is my device variable:

```
dimmer.set_level!(50)
dimmer.set_level(50)
```

I can read the level fine from `dimmer.level`, but setting it throws this error:
```
NoMethodError: undefined method `set_level' for #<MiOS::Device:0x000...>
from ~/.rvm/gems/ruby-2.1.5/gems/mios-0.3.1/lib/mios/device.rb:12:in `method_missing'
```

Any thoughts what I'm doinking here? :smiley_cat:

**Comment by kreynolds** [comment]
I just added an actual dimmer a few days ago but haven't had a chance to fiddle with it yet .. I'll come back to this when I do and either give you a concrete example or fix whatever is broken about it.

**Comment by brock** [comment]
Many thanks sir!

**Comment by kreynolds** [comment]
Fixed with https://github.com/kreynolds/ruby-mios/commit/3ae13091d861f5e476a924f72189992f859dd875
